spring:
  profiles:
    active:
      - local

---
spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    master:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
    slave:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password: